<?php
	VRS_RUNTIME_WWW::HTML_TITLE('Web Map');
?>

<div id="map"></div>
 
<button id="fly"><strong>Reset View</strong></button>

<div id="menu" class="menu">
	<input id="cktc5285n01i617n776r8cr3k" type="radio" name="rtoggle" value="light" checked="checked">
	
	<label for="cktc5285n01i617n776r8cr3k">Light</label> &nbsp;&nbsp;
	<input id="cktls5l3g13e018qr1qm2astp" type="radio" name="rtoggle" value="dark">
	<label for="cktls5l3g13e018qr1qm2astp">Dark</label>
	
</div>